version: "3"
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    tty: true
    ports:
      - 1323:1323
    volumes:
      - .:/go/src/app
    depends_on:
      - redis
  redis:
    image: redis:6.2.6